### ISSUE TITLE
NullReferenceException with RuleOverrideTiles

### ISSUE THREAD

**Issue by jossparlazuyd** [Unity-Technologies/2d-extras#100] opened 2019-05-25 10:46 UTC
Not sure if helpfull but some systeminfo:
Unity version: 2019 1.3f1
OS: Windows 10 latest updates

My situation:
I have 1 main ruleTile which functions as a placable wall.
For this ruleTile i have 6 ruleOverridetiles each with different sprites so that they connect with eachother.

Now, this works well inside Unity, i can place and play with them in the editor and in runtime. But once i build the game it gives me the following exception

``NullReferenceException: Object reference not set to an instance of an object.
UnityEngine.RuleTile.RuleMatches(UnityEngine.Ruletile+Tilingrule rule, UnityEngine.Tilemaps.TileBase[]& neighboringTiles, System.Int32 angle)``

And a second exception following this:

``Error running GetTileData for new TileNullReferenceException: Object reference not set to an instance of an object. UnityEngine.RuleTile.RuleMatches(UnityEngine.RuleTile+TilingRule rule, UnityEngine.Tilemaps.Tilebase[]& neighboringTiles, System.Int32 angle)``

What could be the cause of this? am i using the ruleOverrideTile wrong?

**Comment by johnsoncodehk** [comment] 2019-05-25 12:48
Thank you for proposing this problem.
I can't reproduce this error. Do you mind emailing me your project? (Let me see what happened)
And what is your build target?

**Comment by jossparlazuyd** [comment] 2019-05-25 12:59
My targetplatform is Windows and yeah i don't mind if that could fix the issue. currently i'm clueless as to what is the problem. i'll send it to you in a moment.

**Comment by johnsoncodehk** [comment] 2019-05-25 13:01
Thanks, I will try to solve it as soon as possible.

**Comment by ChuanXin-Unity** [comment] 2019-06-10 07:41
Merged to master. Thanks for the help!

**Closed** 2019-10-17 09:10 UTC
